management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev   # puedes agregar más tags si quieres
    export:
      prometheus:
        enabled: true
        step: 5s # frecuencia con la que Micrometer envía datos a Prometheus

spring:
  application:
    name: ms-backend-metrics

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
